### ISSUE TITLE
No visual editor available for type 'custom:config-template-card'.

### ISSUE THREAD

**Issue by LazzaAU** [iantrich/config-template-card#105] opened 2022-05-27 11:24 UTC
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
Home Assistant Core 2022.5.5
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.1
Kernel version 5.15.32-v8

custom card version = 1.3.6

**Last working release (if known):**

**Browser and Operating System:**
Firefox
Linux - Ubuntu 20.4 ?

Same issue using chrome 

**Description of problem:**
i get the error of ```No visual editor available for type 'custom:config-template-card'.``` I have installed using HACS. It's highly possible i've simply done something wrong as i'm new to this side of HA addons etc 

I'm expecting the weather webpage card to display but it doesnt. the custom card code is 

>type: custom:config-template-card
variables:
  LAT: states['person.larry.latitude'].state
  LON: states['person.larry.longitude'].state
entities:
  - person.larry
card:
  type: iframe
  url: >-
    ${"https://embed.windy.com/embed2.html?lat="+LAT+"&lon="+LON+"&detailLat="+LAT+"&detailLon="+LON+"&width=650&height=450&zoom=10&level=surface&overlay=wind&product=ecmwf&menu=&message=&marker=&calendar=now&pressure=&type=map&location=coordinates&detail=true&metricWind=default&metricTemp=default&radarRange=-1"}
  aspect_ratio: 120%

**Javascript errors shown in the web inspector (if applicable):**

only errors i see in the console that are related are ...
```
The main 'lit-element' module entrypoint is deprecated. Please update your imports to use the 'lit' package: 'lit' and 'lit/decorators.ts' or import from 'lit-element/lit-element.ts'. See https://lit.dev/msg/deprecated-import-path for more information. config-template-card.js:329:12
```

**Additional information:**

**Comment by liudger** [comment] 2022-07-14 14:31
I got the same issue

**Comment by deBoulangerie** [comment] 2022-07-25 08:43
someone found a fix for this?

**Comment by ildar170975** [comment] 2023-07-05 22:03
> LAT: states['person.larry.latitude'].state
> LON: states['person.larry.longitude'].state

This is definitely wrong.
Should be kind of
```
states['person.larry'].attributes['latitude']
```

**Closed by ildar170975** 2023-07-05 22:03 UTC
Labels: bug

**Comment by SvenVdv** [comment] 2025-10-28 09:31
I'm still having this issue in 1.3.6.:

```
Visual editor not supported
The visual editor is not available for this type of element.
You can still edit your config using YAML.
```

**Comment by ildar170975** [comment] 2025-10-28 22:06
> Visual editor not supported

Not a bug. The card is defined in yaml mode only.
