### ISSUE TITLE
Cannot use variables inside card_mod section

### ISSUE THREAD

**Issue by svb91** [iantrich/config-template-card#150] opened 2024-10-30 08:39 UTC
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:** 1.3.6

**Browser and Operating System:** All

I want to use the defined variables (LIGHT_COLOR__EG_GA_L_TERASSE, BRIGHTNESS__EG_GA_L_TERASSE) inside the card_mod section. However, the value will not be passed through and remains empty (without an error).
How can I archive this, as this cards will be wrapped in a decluttering card in the future and therefore I need the variables 

```
`type: custom:config-template-card
         variables:
            LIGHT_COLOR__EG_GA_L_TERASSE: states['light.eg_ga_l_hochbeet'].attributes.hs_color
            BRIGHTNESS__EG_GA_L_TERASSE: states['light.eg_ga_l_hochbeet'].attributes.brightness
          entities:
            - light.eg_ga_l_hochbeet
          card:
            type: picture-elements
            image: /local/images/TEST/transparent.png
            state_image:
              "on": /local/images/RENDERINGS/LICHTER/BACK/EG_GA_L_Terasse.png
            entity: light.eg_ga_l_hochbeet
            elements:
              - type: image
                image: /local/images/TEST/transparent.png
            card_mod:
              style: |
                ha-card {
                  position: absolute;
                  top: 0px;
                  border-radius: 0px !important;
                  mix-blend-mode: lighten;
                  pointer-events: none;
                  filter: opacity({{BRIGHTNESS__EG_GA_L_TERASSE}}%) hue-rotate({{ states['light.eg_ga_l_hochbeet'].attributes.hs_color[0]|int}}deg) saturate(500%)
                }
                ha-card #root {
                  height: calc(100vh - 50px);
                  overflow: hidden !important;
                }
                hui-image {
                  height: calc(100vh - 50px);
                }
                "hui-image $":
                  "img": {
                    object-fit: contain;
                  }`
```

**Comment by MarcStocker** [comment] 2024-10-30 09:37
You are rendering the "style" block incorrectly. Templates must be enclosed in `${ }`. So in order to properly use the template variables here, you have to wrap your entire "style" block in the `${ }`. 

Please try this code instead (I used "top:" as my only test to make sure it worked. I did not attempt to get "opacity" and "hue-rotate" working)
```yaml
    style: |-
      ${
        "ha-card {" + "\n" +
        "  top: "+LIGHT_COLOR__EG_GA_L_TERASSE+"px;" + "\n" +
        "  border-radius: 0px !important;" + "\n" +
        "  filter: opacity("+LIGHT_COLOR__EG_GA_L_TERASSE+"%) hue-rotate("+BRIGHTNESS__EG_GA_L_TERASSE+"deg) saturate(5%" + "\n" +
        "}" + "\n" +
        "ha-card #root {" + "\n" +
        "  height: calc(100vh - 50px);" + "\n" +
        "  overflow: hidden !important;" + "\n" +
        "}" + "\n" +
        "hui-image {" + "\n" +
        "  height: calc(100vh - 50px);" + "\n" +
        "}" + "\n" 
      }
```

~~Because the `${}` renders as javascript, you have to treat anything inside it that's supposed to be plain text as a string. Which also means, you have to explicitly add newline characters as I have.~~ As ildar mentions below, the "\n" are completely unnecessary. 
Hope this helps!

**Comment by ildar170975** [comment] 2024-10-30 14:17
@svb91 
Although it is useful to know how to use `config-template-card` (CTC) variables in card-mod - the initial task is rather incorrect:
1. It is highly unrecommanded to place picture-elements (PE) card inside CTC. Use CTC for a particular element only - if CTC is needed for this particular element only. I see that you are using CTC for a whole PE, not for an element (i.e. this point 1 is not related to your case) - so see point 2.
2. In your example you are using CTC only to declare a variable which is used in card-mod. This is useless and only wastes resources. Card-mod supports jinja - so you can use `states('sensor.xxx')` or `state_attr('sensor.xxx','some_attr')` inside card-mod.

No need to create a monstrous complex code like that mix "card-mod + JS" which is hard to read & maintain and which is a waste of resources.

**Comment by ildar170975** [comment] 2024-10-30 14:22
@svb91 
I am closing this issue since this is not a bug but a question.
This discussion may be continued of course.
Suggest to use CTC only where it is actually needed.
Here is a good place to discuss this card & ask questions: https://community.home-assistant.io/t/100-templatable-lovelace-configurations/105241

**Closed as completed by ildar170975** 2024-10-30 14:22 UTC

**Comment by ildar170975** [comment] 2024-10-30 14:32
@MarcStocker 
Regarding this:
```
"ha-card #root {" + "\n" +
        "  height: calc(100vh - 50px);" + "\n" +
        "  overflow: hidden !important;" + "\n" +
        "}" + "\n" +
        "hui-image {"
```
This is not needed since a card-mod creates a STRING which can be single-line, i.e. 
```
style: |
  ha-card {
    position: absolute;
    top: 0px;
  }
  ha-card #root {
    height: calc(100vh - 50px);
    overflow: hidden !important;
  }
```
is same as
```
style:  "ha-card { position: absolute; top: 0px; } ha-card #root { height: calc(100vh - 50px); overflow: hidden !important;}"
```
So, these "\n" not needed.

**Comment by MarcStocker** [comment] 2024-10-30 19:01
> This is not needed since a card-mod creates a STRING which can be single-line

Ah yes, you are correct. I pulled directly from a Markdown example card I had that needed the "\n" for visual formatting reasons. And somehow failed to get it to render properly without them. 

So this does render just fine without the need for the "\n":

```yaml
card_mod:
    style: |-
      ${
        "ha-card {" + 
        "  top: " + TEMPLATE_VARIABLE + "px;" + 
        "  border-radius: 0px !important;" + 
        "}"
      }
```
